name: "pr-title-checker"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - dev
      - main

permissions:
  pull-requests: read

jobs:
  validate_pr_title:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'merge_group' }}
    steps:
      - name: Check PR title
        run: |
          echo "hello valen test"
