name: Echo Environment Variable

on:
  push:
    branches:
      - main

jobs:
  set-and-echo-env:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Environment Variable
        shell: pwsh
        run: |
          .\scripts\test.ps1

      - name: Echo Environment Variable
        shell: pwsh
        run: |
          Write-Host "The value of rg_name is: $Env:rg_name"
