name: Echo Environment Variable

on:
  push:
    branches:
      - main

jobs:
  set-and-echo-env:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Purging the Resources
        if: success()
        run: |
              if (-not (mkdir test)) {
              Write-Host "Failed to purge OpenAI resource."
              }


      # - name: Echo Environment Variable
      #   run: |
      #     echo "The value of rg_name is: ${{ env.rg_name }}"
