name: Echo Environment Variable

on:
  push:
    branches:
      - main

# jobs:
#   set-and-echo-env:
#     runs-on: windows-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3
#       # Set up Docker
#       - name: Set up Docker
#         uses: docker/setup-buildx-action@v2
#         with:
#           driver: docker

#       # Verify Docker setup
#       - name: Verify Docker installation
#         run: docker --version

#       # - name: Purging the Resources
#       #   if: success()
#       #   run: |


#       #         # Declare the variables
#       #         $aName = "hello"
              
 
#       #         # Check if $a equals "hello"
#       #         if ($aName -eq "hello") {
#       #           Write-Host "/hi/$aName"
#       #         }

#       #           $b = "bye"
#       #         if (-not $?) {
#       #         Write-Host "Failed to purge OpenAI resource."
#       #         }
              
#       #         # Check if $b equals "bye"
#       #         if ($b -eq "bye") {
#       #           Write-Host "/hey/$bye"
#       #         }
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: frontend
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - run: npm ci
    - run: NODE_OPTIONS=--max_old_space_size=8192 npm run build --if-present
    - run: npm run test --if-present


      # - name: Echo Environment Variable
      #   run: |
      #     echo "The value of rg_name is: ${{ env.rg_name }}"
