name: Run PowerShell Script

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-powershell-script:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run PowerShell Script
        shell: pwsh
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process
          .\scripts\test.ps1
