name: Echo Environment Variable

on:
  push:
    branches:
      - main

jobs:
  set-and-echo-env:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Purging the Resources
        if: success()
        run: |


              # Declare the variables
              $aName = "hello"
              
 
              # Check if $a equals "hello"
              if ($a -eq "hello") {
                Write-Host "/hi/${{aName}}"
              }

                $b = "bye"
              if (-not $?) {
              Write-Host "Failed to purge OpenAI resource."
              }
              
              # Check if $b equals "bye"
              if ($b -eq "bye") {
                Write-Host "/hey/$bye"
              }


      # - name: Echo Environment Variable
      #   run: |
      #     echo "The value of rg_name is: ${{ env.rg_name }}"
